name: all

on:
  workflow_dispatch: {}
  push: {}
  schedule:
    #         ┌───────────── minute (0 - 59)
    #         │ ┌───────────── hour (0 - 23)
    #         │ │ ┌───────────── day of the month (1 - 31)
    #         │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #         * * * * *
    - cron:  '0 0 * * 3'

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml

  acceptance:
    uses: ./.github/workflows/reusable-acceptance.yml
    secrets:
      license_encryption_password: ${{ secrets.LICENSE_ENCRYPTION_PASSWORD }}
