name: pr-acceptance

on:
  pull_request_target:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'

jobs:
  acceptance:
    uses: ./.github/workflows/reusable-acceptance.yml
    with:
      head_sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      license_encryption_password: ${{ secrets.LICENSE_ENCRYPTION_PASSWORD }}
