# Acceptance test jobs can take 30 minutes to run and require running in the target repository in
# order to read secrets. If no license_encryption_password secret is passed in, then the
# acceptance-ee job is ignored.

on:
  workflow_call:
    inputs:
      head_sha:
        type: string
    secrets:
      license_encryption_password: {}

jobs:
  go-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.head_sha }}
      - id: go-version
        run: echo "::set-output name=go-version::$(cat .go-version)"

  # Check whether license_encryption_password was passed in.
  # Workaround for https://github.com/actions/runner/issues/520.
  password:
    runs-on: ubuntu-latest
    outputs:
      defined: ${{ steps.defined.outputs.defined }}
    steps:
      - id: defined
        env:
          PASSWORD: ${{ secrets.license_encryption_password }}
        if: ${{ env.PASSWORD != '' }}
        run: echo "::set-output name=defined::true"

  acceptance-ce:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [go-version]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-version.outputs.go-version }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.head_sha }}
      - run: make testacc-up
      - run: make testacc

  acceptance-ee:
    if: ${{ needs.password.outputs.defined }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [go-version, password]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-version.outputs.go-version }}
      - uses: actions/checkout@v2
      - name: Decrypt license
        run: |
          openssl version
          openssl enc -d -aes-256-cbc -pbkdf2 -iter 20000 -in Gitlab-license.encrypted -out Gitlab-license.txt -pass "pass:${{ secrets.license_encryption_password }}"
      - run: make testacc-up SERVICE=gitlab-ee
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.head_sha }}
      - run: make testacc
